# Generated by Django 5.1.7 on 2025-03-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_populate_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='temp', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
